### ISSUE TITLE
Morning Session Code Review- 26/05/22

### ISSUE THREAD

**Issue by Epaltechs** [Lusindiso/Javascript-Capstone#38]
It was nice surfing your beautifully designed page. Well done. ![image](https://user-images.githubusercontent.com/91189703/170439459-3e806ee9-5971-49f9-b4c3-181240eabbe5.png)
We would suggest you check for and clear the linter errors.

**Comment by BouaikIlham** [comment]
@Lusindiso god job so far nice work clean code :100: :1st_place_medal:
